# Generated by Django 3.1.4 on 2020-12-04 17:24

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('m', 'Men'), ('w', 'Women'), ('k', 'Kids')], default='m', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=shop.models.upload_path),
        ),
    ]
