# Generated by Django 3.1.4 on 2020-12-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('2', 'UK2'), ('2.5', 'UK2.5'), ('3', 'UK3'), ('3.5', 'UK3.5'), ('4', 'UK4'), ('4.5', 'UK4.5'), ('5', 'UK5'), ('5.5', 'UK5.5'), ('6', 'UK6'), ('6.5', 'UK6.5'), ('7', 'UK7'), ('7.5', 'UK7.5'), ('8', 'UK8'), ('8.5', 'UK8.5'), ('9', 'UK9'), ('9.5', 'UK9.5'), ('10', 'UK10')], default='8', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='m', max_length=10),
        ),
    ]
